// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qweftawwgjxammyqlpki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3ZWZ0YXd3Z2p4YW1teXFscGtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTkxNTQsImV4cCI6MjA2NzczNTE1NH0.o2QUF_rCURKr_PJn4NAduuxBhBcH-eHwVAlxKKkD0Rs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});